language: objective-c

notifications:
  slack: devlucky:0AP12qjjfc2Zxc0s9yo1cQQm

env:
  global:
    - FASTLANE_LANE=ci_commit

before_install:
  - gem uninstall json -v 2.0.1 # workaround for Fastlane conflict https://github.com/travis-ci/travis-ci/issues/6325
  - gem install danger danger-prose --no-ri --no-doc

before_script:
  - danger

matrix:
  include:
    - osx_image: xcode7.3
      env: FASTLANE_ENV=ios83
    - osx_image: xcode7.3
      env: FASTLANE_ENV=tvos
    - osx_image: xcode7.3
      env: FASTLANE_ENV=osx1011
    - osx_image: xcode7.3
      env: FASTLANE_ENV=ios93 KKP_CODECOV=true
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J 'Kakapo'

script:
  - set -o pipefail
  - fastlane $FASTLANE_LANE configuration:Debug --env $FASTLANE_ENV
  - pod lib lint --quick

podfile: Podfile

after_failure:
  - cat -n ~/Library/Logs/scan/*
  - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
  - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash

