language: objective-c
cache:
  - bundler

notifications:
  slack: devlucky:0AP12qjjfc2Zxc0s9yo1cQQm

env:
  global:
    - FASTLANE_LANE=ci_commit

matrix:
  include:
    - osx_image: xcode8
      env: FASTLANE_ENV=tvos
    - osx_image: xcode8
      env: FASTLANE_ENV=osx
    - osx_image: xcode8
      env: FASTLANE_ENV=ios93
    - osx_image: xcode8
      env: FASTLANE_ENV=ios10 KKP_CODECOV=true
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J 'Kakapo'

script:
  - set -o pipefail
  - fastlane $FASTLANE_LANE configuration:Debug --env $FASTLANE_ENV
  - pod lib lint --quick
  - bundle exec danger

podfile: Podfile

after_failure:
  - cat -n ~/Library/Logs/scan/*
  - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
  - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash

# sleep a bit -> https://github.com/travis-ci/travis-ci/issues/4725
after_success:
  - sleep 10
